#!/usr/bin/env bash
set -eux
as -ggdb3 --32 -o entry.o entry.S
gcc -c -ggdb3 -m16 -ffreestanding -fno-PIE -nostartfiles -nostdlib -o input.o -std=c99 input.c
ld -m elf_i386 -o input.elf -T linker.ld entry.o input.o
objcopy -O binary input.elf input.img
qemu-system-x86_64 -drive file=input.img,format=raw
