#!/usr/bin/env bash
set -eux
as -ggdb3 --32 -o entry.o entry.S
gcc -c -ggdb3 -m16 -ffreestanding -fno-PIE -nostartfiles -nostdlib -o rand.o -std=c99 rand.c
ld -m elf_i386 -o input.elf -T linker.ld entry.o rand.o
qemu-system-x86_64 -drive file=input.img,format=raw
